# -*- mode: ruby -*-
# vi: set ft=ruby :
#

chef_run_list = %w(
  apt
  java::default
  curl::default
  logstash::agent
  grantoo_kinesis_logstash::default
)

chef_json = {
  java: {
    jdk_version: '7'
  },
  logstash: {
    instance: { agent: {} }
  },

  kinesis_logstash: {
    input: {
      aws_credentials: ["yey-change-me", "yey-change-me"],
      bucket: "kinesis-radar-analytics"
    },
    output: {
      host: "http://example.com",
      port: 80,
      user: "moo",
      password: "moo"
    }
  }
}

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.require_version ">= 1.5.0"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.hostname = "grantoo-kinesis-logstash-berkshelf"

  config.omnibus.chef_version = :latest

  config.vm.box = "opscode-ubuntu-12.04"
  config.vm.box_url   = 'https://opscode-vm-bento.s3.amazonaws.com/vagrant/opscode_ubuntu-12.04_provisionerless.box'

  config.berkshelf.enabled = true

  config.vm.provider :virtualbox do |vb|
    vb.customize ['modifyvm', :id, '--memory', '1024']
  end

  config.vm.provision :chef_solo do |chef|
    chef.log_level = 'info'
    chef.json = chef_json

    chef.run_list = chef_run_list
  end
end
